# Generated by Django 3.1.6 on 2022-05-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220503_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=250),
        ),
    ]
