# Generated by Django 3.1.6 on 2022-05-02 18:48

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220503_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(default=django.db.models.fields.Field.value_to_string, max_length=250),
        ),
    ]
