# Generated by Django 3.1.6 on 2022-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='inp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(default=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++')], default='python', max_length=6), max_length=250),
        ),
    ]
