# Generated by Django 3.1.6 on 2022-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220502_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++')], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(default=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++')], default='python', max_length=10), max_length=250),
        ),
    ]
